-- MySQL Script generated by MySQL Workbench
-- Thu Jul 18 22:27:06 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema Railway_station
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Railway_station
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Railway_station` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `Railway_station` ;

-- -----------------------------------------------------
-- Table `Railway_station`.`Drivers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Drivers` (
  `Id` INT(11) NOT NULL AUTO_INCREMENT,
  `workers_id` INT(11) NULL DEFAULT NULL,
  `trips_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`),
  INDEX `drivers_workers_id_fk` (`workers_id` ASC) ,
  INDEX `drivers_trips_id_fk` (`trips_id` ASC),
  CONSTRAINT `drivers_trips_id_fk`
    FOREIGN KEY (`trips_id`)
    REFERENCES `Railway_station`.`trips` (`id`),
  CONSTRAINT `drivers_workers_id_fk`
    FOREIGN KEY (`workers_id`)
    REFERENCES `Railway_station`.`workers` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Passengers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `surname` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 22
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Seats` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nomber` INT(11) NOT NULL,
  `trucks_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `seats_trucks_id_fk` (`trucks_id` ASC),
  CONSTRAINT `seats_trucks_id_fk`
    FOREIGN KEY (`trucks_id`)
    REFERENCES `Railway_station`.`trucks` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 164
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Specialities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Stations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `train_routes_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `stations_train_routes_id_fk` (`train_routes_id` ASC),
  CONSTRAINT `stations_train_routes_id_fk`
    FOREIGN KEY (`train_routes_id`)
    REFERENCES `Railway_station`.`train_routes` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 132
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Tickets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `price` FLOAT NOT NULL,
  `linens` TINYINT(1) NULL DEFAULT '0',
  `passengers_id` INT(11) NULL DEFAULT NULL,
  `trips_id` INT(11) NULL DEFAULT NULL,
  `seats_id` INT(11) NULL DEFAULT NULL,
  `trains_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `tickets_passengers_id_fk` (`passengers_id` ASC),
  INDEX `tickets_seats_id_fk` (`seats_id` ASC) ,
  INDEX `tickets_trips_id_fk` (`trips_id` ASC) ,
  INDEX `tickets_trains_id_fk` (`trains_id` ASC),
  CONSTRAINT `tickets_passengers_id_fk`
    FOREIGN KEY (`passengers_id`)
    REFERENCES `Railway_station`.`passengers` (`id`),
  CONSTRAINT `tickets_seats_id_fk`
    FOREIGN KEY (`seats_id`)
    REFERENCES `Railway_station`.`seats` (`id`),
  CONSTRAINT `tickets_trains_id_fk`
    FOREIGN KEY (`trains_id`)
    REFERENCES `Railway_station`.`trucks` (`id`),
  CONSTRAINT `tickets_trips_id_fk`
    FOREIGN KEY (`trips_id`)
    REFERENCES `Railway_station`.`trips` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Train_blocks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Train_blocks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `trains_id` INT(11) NULL DEFAULT NULL,
  `trucks_id` INT(11) NULL DEFAULT NULL,
  `trips_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `train_blocks_trains_id_fk` (`trains_id` ASC),
  INDEX `train_blocks_trucks_id_fk` (`trucks_id` ASC),
  INDEX `train_blocks_trips_id_fk` (`trips_id` ASC),
  CONSTRAINT `train_blocks_trains_id_fk`
    FOREIGN KEY (`trains_id`)
    REFERENCES `Railway_station`.`trains` (`id`),
  CONSTRAINT `train_blocks_trips_id_fk`
    FOREIGN KEY (`trips_id`)
    REFERENCES `Railway_station`.`trips` (`id`),
  CONSTRAINT `train_blocks_trucks_id_fk`
    FOREIGN KEY (`trucks_id`)
    REFERENCES `Railway_station`.`trucks` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 46
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `Railway_station`.`Train_routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Train_routes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `departure_time` DATETIME NOT NULL,
  `arrival_time` DATETIME NOT NULL,
  `distance` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Train_timetables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Train_timetables` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `railway_nomber` VARCHAR(4) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `trips_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `train_timetables_trips_id_fk` (`trips_id` ASC),
  CONSTRAINT `train_timetables_trips_id_fk`
    FOREIGN KEY (`trips_id`)
    REFERENCES `Railway_station`.`trips` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Train_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Train_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Trains` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `train_number` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `train_routes_id` INT(11) NULL DEFAULT NULL,
  `train_types_id` INT(11) NULL DEFAULT NULL,
  `stations_departure_id` INT(11) NULL DEFAULT NULL,
  `stations_arrival_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `trains_stations_arrival_id_fk` (`stations_arrival_id` ASC),
  INDEX `trains_stations_departure_id_fk` (`stations_departure_id` ASC),
  INDEX `trains_train_routes_id_fk` (`train_routes_id` ASC),
  INDEX `trains_train_types_id_fk` (`train_types_id` ASC),
  CONSTRAINT `trains_stations_arrival_id_fk`
    FOREIGN KEY (`stations_arrival_id`)
    REFERENCES `Railway_station`.`stations` (`id`),
  CONSTRAINT `trains_stations_departure_id_fk`
    FOREIGN KEY (`stations_departure_id`)
    REFERENCES `Railway_station`.`stations` (`id`),
  CONSTRAINT `trains_train_routes_id_fk`
    FOREIGN KEY (`train_routes_id`)
    REFERENCES `Railway_station`.`train_routes` (`id`),
  CONSTRAINT `trains_train_types_id_fk`
    FOREIGN KEY (`train_types_id`)
    REFERENCES `Railway_station`.`train_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Trips` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `trains_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `trips_trains_id_fk` (`trains_id` ASC),
  CONSTRAINT `trips_trains_id_fk`
    FOREIGN KEY (`trains_id`)
    REFERENCES `Railway_station`.`trains` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Truck_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Truck_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 12
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Trucks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Trucks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `seats_amount` INT(11) NOT NULL,
  `truck_types_id` INT(11) NULL DEFAULT NULL,
  `train_types_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `trucks_truck_types_id_fk` (`truck_types_id` ASC),
  INDEX `trucks_train_types_id_fk` (`train_types_id` ASC),
  CONSTRAINT `trucks_train_types_id_fk`
    FOREIGN KEY (`train_types_id`)
    REFERENCES `Railway_station`.`train_types` (`id`),
  CONSTRAINT `trucks_truck_types_id_fk`
    FOREIGN KEY (`truck_types_id`)
    REFERENCES `Railway_station`.`truck_types` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


-- -----------------------------------------------------
-- Table `Railway_station`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Railway_station`.`Workers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `surname` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `salary` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `specialities_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `workers_specialities_id_fk` (`specialities_id` ASC),
  CONSTRAINT `workers_specialities_id_fk`
    FOREIGN KEY (`specialities_id`)
    REFERENCES `Railway_station`.`specialities` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
