-- MySQL Script generated by MySQL Workbench
-- Fri Jul 19 09:33:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema railway
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `railway` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `railway` ;

-- -----------------------------------------------------
-- Table `railway`.`Passengers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Passengers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Routes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Routes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `distance` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Seats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Seats` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nomber` INT(4) NOT NULL,
  `trucks_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Seats_Trucks1_idx` (`trucks_id` ASC) VISIBLE,
  CONSTRAINT `fk_Seats_Trucks1`
    FOREIGN KEY (`trucks_id`)
    REFERENCES `railway`.`Trucks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 163
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Specialities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Specialities` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Stations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Stations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  `routes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Stations_Routes1_idx` (`routes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Stations_Routes1`
    FOREIGN KEY (`routes_id`)
    REFERENCES `railway`.`Routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 132
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Tickets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Tickets` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `price` INT(11) NULL DEFAULT NULL,
  `linens` TINYINT(1) NULL DEFAULT NULL,
  `passengers_id` INT(11) NOT NULL,
  `trains_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tickets_Passengers1_idx` (`passengers_id` ASC) VISIBLE,
  INDEX `fk_Tickets_Trains1_idx` (`trains_id` ASC) VISIBLE,
  CONSTRAINT `fk_Tickets_Passengers1`
    FOREIGN KEY (`passengers_id`)
    REFERENCES `railway`.`Passengers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tickets_Trains1`
    FOREIGN KEY (`trains_id`)
    REFERENCES `railway`.`Trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 16
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Timetables`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Timetables` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `railway_nomber` INT(11) NOT NULL,
  `departure_date` DATETIME NOT NULL,
  `routes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Timetables_Routes1_idx` (`routes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Timetables_Routes1`
    FOREIGN KEY (`routes_id`)
    REFERENCES `railway`.`Routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Trailers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Trailers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Train_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Train_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Train_workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Train_workers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `workers_id` INT(11) NOT NULL,
  `trains_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Train_workers_Workers1_idx` (`workers_id` ASC) VISIBLE,
  INDEX `fk_Train_workers_Trains1_idx` (`trains_id` ASC) VISIBLE,
  CONSTRAINT `fk_Train_workers_Workers1`
    FOREIGN KEY (`workers_id`)
    REFERENCES `railway`.`Workers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Train_workers_Trains1`
    FOREIGN KEY (`trains_id`)
    REFERENCES `railway`.`Trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 17
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Trains`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Trains` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `train_types_id` INT(11) NOT NULL,
  `trailers_id` INT(11) NOT NULL,
  `routes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Trains_Train_types1_idx` (`train_types_id` ASC) VISIBLE,
  INDEX `fk_Trains_Trailers1_idx` (`trailers_id` ASC) VISIBLE,
  INDEX `fk_Trains_Routes1_idx` (`routes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Trains_Train_types1`
    FOREIGN KEY (`train_types_id`)
    REFERENCES `railway`.`Train_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trains_Trailers1`
    FOREIGN KEY (`trailers_id`)
    REFERENCES `railway`.`Trailers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trains_Routes1`
    FOREIGN KEY (`routes_id`)
    REFERENCES `railway`.`Routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Trips`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Trips` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nomber` VARCHAR(15) NOT NULL,
  `routes_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Trips_Routes1_idx` (`routes_id` ASC) VISIBLE,
  CONSTRAINT `fk_Trips_Routes1`
    FOREIGN KEY (`routes_id`)
    REFERENCES `railway`.`Routes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Truck_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Truck_types` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Trucks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Trucks` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `seats_amount` INT(11) NULL DEFAULT NULL,
  `truck_types_id` INT(11) NOT NULL,
  `trains_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Trucks_Truck_types1_idx` (`truck_types_id` ASC) VISIBLE,
  INDEX `fk_Trucks_Trains1_idx` (`trains_id` ASC) VISIBLE,
  CONSTRAINT `fk_Trucks_Truck_types1`
    FOREIGN KEY (`truck_types_id`)
    REFERENCES `railway`.`Truck_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trucks_Trains1`
    FOREIGN KEY (`trains_id`)
    REFERENCES `railway`.`Trains` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `railway`.`Workers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `railway`.`Workers` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `salary` INT(11) NULL DEFAULT NULL,
  `specialities_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Workers_Specialities1_idx` (`specialities_id` ASC) VISIBLE,
  CONSTRAINT `fk_Workers_Specialities1`
    FOREIGN KEY (`specialities_id`)
    REFERENCES `railway`.`Specialities` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 47
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
